# Generated by Django 4.0.3 on 2022-04-01 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_id_ownedpokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
